"""add total_spent

迁移 ID: b7d2c3e4f5a6
父迁移: a1b2c3d4e5f6
创建时间: 2026-08-28 00:00:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b7d2c3e4f5a6'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_fishing_fishingrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_spent', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_fishing_fishingrecord', schema=None) as batch_op:
        batch_op.drop_column('total_spent')

    # ### end Alembic commands ###
